upstream ui_backend {
    server ui1:80;
    server ui2:80;
    server ui3:80;
    server ui4:80;
    server ui5:80;
}

server {
    listen 80;

    location / {
        proxy_pass http://ui_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
